# Generated by Django 6.0.3 on 2026-05-03 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_types',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('jira_project_name', models.CharField(blank=True, max_length=150, null=True)),
                ('jira_board_link', models.URLField(blank=True, null=True)),
                ('workstream', models.CharField(blank=True, max_length=150, null=True)),
                ('agile_practices', models.TextField(blank=True, null=True)),
                ('concurrent_projects', models.CharField(blank=True, max_length=20, null=True)),
                ('development_focus', models.TextField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('versioning_approach', models.TextField(blank=True, null=True)),
                ('slack_channels', models.TextField(blank=True, null=True)),
                ('daily_standup_link', models.URLField(blank=True, null=True)),
                ('team_wiki_url', models.URLField(blank=True, null=True)),
                ('wiki_search_terms', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('restructured', 'Restructured'), ('disbanded', 'Disbanded')], default='active', max_length=20)),
                ('disbanded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='department.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('team_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.teamtype')),
            ],
            options={
                'db_table': 'team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_member',
                'ordering': ['-joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
