# Generated by Django 6.0.3 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teammember_table_contactchannel_repository_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Senior Engineer', 'Senior Engineer'), ('Team Lead', 'Team Lead'), ('Product Manager', 'Product Manager'), ('Agile Coach', 'Agile Coach'), ('QA Engineer', 'QA Engineer'), ('Designer', 'Designer')], default='Software Engineer', max_length=100),
        ),
    ]
