# Generated by Django 6.0.3 on 2026-05-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
