# Generated by Django 6.0.3 on 2026-05-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='teams.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='teams.team')),
            ],
            options={
                'db_table': 'team_dependency',
                'ordering': ['from_team__name', 'to_team__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_team', models.F('to_team')), _negated=True), name='team_dependency_no_self_reference')],
                'unique_together': {('from_team', 'to_team')},
            },
        ),
    ]
