# Generated by Django 6.0.3 on 2026-05-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teamdependency'),
        ('teams', '0002_skill_team_email_address_team_is_active_and_more'),
    ]

    operations = []
