# Generated by Django 6.0.3 on 2026-05-04 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_teamdependency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meeting title or subject', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Agenda or meeting details', null=True)),
                ('scheduled_at', models.DateTimeField(help_text='When the meeting is scheduled')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Meeting duration in minutes')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for the meeting', max_length=50)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('google_meet', 'Google Meet'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='zoom', help_text='Meeting platform (Zoom, Teams, etc.)', max_length=50)),
                ('meeting_link', models.URLField(blank=True, help_text='Video call or meeting link', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the meeting', max_length=20)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='none', help_text='Recurrence pattern', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organiser', models.ForeignKey(help_text='User who created the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='organised_meetings', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Associated team (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='teams.team')),
            ],
            options={
                'db_table': 'meeting',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='pending', help_text='RSVP status for this attendee', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(help_text='The meeting this attendee is registered for', on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='scheduling.meeting')),
                ('user', models.ForeignKey(help_text='User attending the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_attendee',
                'ordering': ['rsvp_status', 'user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organiser', 'scheduled_at'], name='meeting_organis_fe194b_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_at'], name='meeting_status_f7a350_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['team', 'scheduled_at'], name='meeting_team_id_0bde32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendee',
            unique_together={('meeting', 'user')},
        ),
    ]
