# Generated by Django 6.0.3 on 2026-05-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='head_user',
            new_name='head',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
